### ISSUE TITLE
Does not work after uipdate from 9.4 :(

### ISSUE THREAD

**Issue by michalss** [camposantogames/firewatch_localization#11]
Can you please fix it, after update 9.4 you added some crappy languages, but it wont take any others from AppData anymore :( Why ??? We have done localization and we cannot use it coz of this. Fix it pls...

**Comment by hoverbird** [comment]
This is a bug- we're looking into it now. Thanks for reporting, we will have a fix ASAP!

**Comment by hoverbird** [comment]
@michalss are you on a Mac by any chance?

**Comment by michalss** [comment]
nope im on PC Win

**Comment by michalss** [comment]
After today update, still does not work and it still wont take any lang from appdata :(

**Comment by hoverbird** [comment]
We believe this is simply that the dropdown menu doesn't scroll, and other languages are being pushed to the bottom. We are working on a fix for this now. Does this sound like it could be the issue you are experiencing @michalss ?

**Comment by michalss** [comment]
yes possible, all langs wont fit into scroll menu in any case, so it could be this problem. I guess to move this combo box somwhere on the top of the settings could help, but if you think about more pernament solution, move it at the top and make font smaller... :) BTW thank you for Czech Fonts..

**Comment by michalss** [comment]
nice it is fixed :D thx a lot. Any chance to have czech as official language ?

**Comment by hoverbird** [comment]
We don't currently have plans to expand our official set beyond English, German, Spanish, French, Russian and Chinese, unfortunately.
